import Image from "next/image";
import Link from "next/link";
import { Camera, Clock, ShieldCheck, ArrowsClockwise, UploadSimple, Sparkle, DownloadSimple } from "@phosphor-icons/react/dist/ssr";
import { STYLES } from "@/lib/styles";
import { brand } from "@/lib/brand";
import { PLANS, formatUsd } from "@/lib/plans";
import { StyleCard } from "@/components/samples";
import { Pricing } from "@/components/pricing";
import { Faq, faqJsonLd } from "@/components/faq";
import { NewsletterForm } from "@/components/newsletter-form";

const DEMO = (t: string) => `/api/brand-kit-demo/${t}`;

export default function Home() {
  const productLd = {
    "@context": "https://schema.org",
    "@type": "Product",
    name: `${brand.name} AI Realtor Headshots`,
    description: "AI headshots and marketing brand kit for real estate agents.",
    brand: { "@type": "Brand", name: brand.name },
    offers: [PLANS.starter, PLANS.pro].map((p) => ({
      "@type": "Offer",
      name: p.name,
      price: (p.priceCents / 100).toFixed(2),
      priceCurrency: "USD",
      availability: "https://schema.org/InStock",
    })),
  };

  return (
    <>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify([productLd, faqJsonLd()]) }} />

      {/* Hero: split, value prop left, real product output right */}
      <section className="mx-auto grid max-w-6xl items-center gap-12 px-4 pb-16 pt-12 md:grid-cols-[1.1fr_1fr] md:pt-20">
        <div>
          <h1 className="font-display text-4xl leading-[1.05] md:text-6xl">
            Realtor headshots that look like <em className="not-italic text-accent">you</em>
          </h1>
          <p className="mt-5 max-w-md text-lg text-muted">
            Upload a few selfies. Get realistic headshots in 12 real estate styles, plus listing graphics, in about an hour.
          </p>
          <div className="mt-8 flex flex-wrap gap-3">
            <Link href="#pricing" className="btn-primary">Get headshots</Link>
            <Link href="/free-just-listed" className="btn-ghost">Try the free graphic maker</Link>
          </div>
        </div>
        <div className="relative mx-auto w-full max-w-md md:max-w-none">
          <Image
            src={DEMO("just-listed")}
            alt="Just Listed graphic generated by the Brand Kit"
            width={1080}
            height={1350}
            priority
            unoptimized
            className="w-[72%] rounded-2xl border border-line shadow-[0_24px_60px_-24px_rgba(20,30,60,0.35)]"
          />
          <Image
            src={DEMO("business-card")}
            alt="Business card graphic generated by the Brand Kit"
            width={1050}
            height={600}
            unoptimized
            className="absolute -bottom-8 right-0 w-[50%] rounded-xl border border-line shadow-[0_24px_60px_-24px_rgba(20,30,60,0.35)]"
          />
        </div>
      </section>

      {/* Trust strip */}
      <section aria-label="What you get" className="border-y border-line bg-card">
        <ul className="mx-auto grid max-w-6xl grid-cols-2 gap-6 px-4 py-6 text-sm md:grid-cols-4">
          {[
            [Camera, "No photographer or scheduling"],
            [ArrowsClockwise, "Free redos on any style"],
            [ShieldCheck, "MLS-safe plain backgrounds"],
            [Clock, "Selfies deleted after 7 days"],
          ].map(([Icon, text]) => {
            const I = Icon as typeof Camera;
            return (
              <li key={text as string} className="flex items-center gap-3 text-muted">
                <I size={20} weight="duotone" className="shrink-0 text-accent" aria-hidden />
                {text as string}
              </li>
            );
          })}
        </ul>
      </section>

      {/* How it works: heading column + stacked steps */}
      <section className="mx-auto grid max-w-6xl gap-10 px-4 py-20 md:grid-cols-[1fr_1.4fr]">
        <div>
          <h2 className="font-display text-3xl md:text-4xl">From selfies to a full brand in an afternoon</h2>
          <p className="mt-3 max-w-sm text-muted">About 10 minutes of your time. The rest happens while you work.</p>
        </div>
        <ol className="divide-y divide-line">
          {[
            [UploadSimple, "Upload 10-20 selfies", "Recent phone photos work. The studio shows you what to include."],
            [Sparkle, "We train your private model", "The AI learns your face, then photographs you in realtor settings. About an hour."],
            [DownloadSimple, "Pick favorites and post", "Download full resolution and turn your favorite into listing graphics in one click."],
          ].map(([Icon, title, body]) => {
            const I = Icon as typeof Camera;
            return (
              <li key={title as string} className="flex gap-5 py-6 first:pt-0">
                <span className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-accent-soft text-accent">
                  <I size={22} weight="duotone" aria-hidden />
                </span>
                <div>
                  <h3 className="text-lg font-semibold">{title as string}</h3>
                  <p className="mt-1 max-w-[52ch] text-muted">{body as string}</p>
                </div>
              </li>
            );
          })}
        </ol>
      </section>

      {/* Styles gallery */}
      <section id="styles" className="mx-auto max-w-6xl scroll-mt-20 px-4 pb-20">
        <h2 className="font-display max-w-2xl text-3xl md:text-4xl">12 styles made for real estate</h2>
        <p className="mt-3 max-w-[60ch] text-muted">Generic headshot apps give you corporate gray. You sell homes, so your photos should look like it.</p>
        <div className="mt-10 grid grid-cols-2 gap-4 sm:grid-cols-3 lg:grid-cols-4">
          {STYLES.map((s) => (
            <StyleCard key={s.id} style={s} />
          ))}
        </div>
      </section>

      {/* Brand kit: same light theme, tinted band */}
      <section id="brand-kit" className="scroll-mt-20 bg-accent-soft">
        <div className="mx-auto grid max-w-6xl items-center gap-12 px-4 py-20 md:grid-cols-[1fr_1.2fr]">
          <div>
            <p className="text-sm font-semibold text-accent">The part other headshot apps skip</p>
            <h2 className="font-display mt-2 text-3xl md:text-4xl">Your headshot, turned into a marketing kit</h2>
            <p className="mt-4 max-w-[52ch] text-muted">
              Agent Pro includes ready-to-post graphics with your photo, brand color and contact details. Your brokerage name is always on them, as NC advertising rules require.
            </p>
            <p className="mt-4 text-sm text-muted">Just Listed, Open House, Under Contract, Sold and Coming Soon, plus a business card, email signature and LinkedIn cover.</p>
          </div>
          <div className="grid grid-cols-3 items-end gap-3">
            {[
              ["open-house", 1080, 1350, "Open House graphic"],
              ["sold", 1080, 1080, "Just Sold graphic"],
              ["under-contract", 1080, 1080, "Under Contract graphic"],
            ].map(([t, w, h, alt], i) => (
              <Image
                key={t as string}
                src={DEMO(t as string)}
                alt={`${alt} generated by the Brand Kit`}
                width={w as number}
                height={h as number}
                unoptimized
                loading="lazy"
                className={`w-full rounded-xl border border-line bg-card ${i === 1 ? "md:-translate-y-8" : ""}`}
              />
            ))}
          </div>
        </div>
      </section>

      {/* Comparison */}
      <section className="mx-auto max-w-4xl px-4 py-20">
        <h2 className="font-display text-3xl md:text-4xl">How we compare</h2>
        <div className="mt-8 overflow-x-auto rounded-2xl border border-line bg-card">
          <table className="w-full min-w-[560px] text-sm">
            <thead className="text-left">
              <tr className="border-b border-line">
                <th className="p-4"><span className="sr-only">Feature</span></th>
                <th className="p-4 text-accent">{brand.name}</th>
                <th className="p-4 font-medium text-muted">Photographer</th>
                <th className="p-4 font-medium text-muted">Generic AI apps</th>
              </tr>
            </thead>
            <tbody className="tabular-nums">
              {[
                ["Typical price", `${formatUsd(PLANS.starter.priceCents)}-${formatUsd(PLANS.pro.priceCents)}`, "$200-$500+", "$29-$75"],
                ["Turnaround", "About 1 hour", "1-2 weeks", "1-3 hours"],
                ["Real estate styles", "12", "1-3 looks", "Corporate"],
                ["Listing and social graphics", "Included", "No", "No"],
                ["Brokerage name on graphics", "Automatic", "No", "No"],
                ["Team ordering", "Yes", "Group sessions", "Some"],
              ].map(([k, a, b, c]) => (
                <tr key={k} className="even:bg-paper/60">
                  <td className="p-4 font-medium">{k}</td>
                  <td className="p-4 font-semibold text-accent">{a}</td>
                  <td className="p-4 text-muted">{b}</td>
                  <td className="p-4 text-muted">{c}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </section>

      <Pricing />

      {/* Teams */}
      <section className="mx-auto max-w-6xl px-4">
        <div className="flex flex-col items-start justify-between gap-6 rounded-2xl bg-accent-soft p-8 md:flex-row md:items-center">
          <div>
            <h2 className="font-display text-2xl md:text-3xl">Matching headshots for your whole office</h2>
            <p className="mt-2 max-w-xl text-muted">One invite link, one invoice, one consistent team look. {formatUsd(PLANS.team.priceCents)} per agent, 5-seat minimum.</p>
          </div>
          <Link href="/teams" className="btn-primary">See team pricing</Link>
        </div>
      </section>

      <Faq />

      <section className="mx-auto max-w-xl px-4">
        <h2 className="font-display text-2xl">Not ready yet?</h2>
        <p className="mt-2 text-sm text-muted">One email a month with post ideas, template drops and headshot advice.</p>
        <div className="mt-4"><NewsletterForm source="homepage" /></div>
      </section>
    </>
  );
}
